name: Documentation
on:
  push:
    branches:
      - 'stable'
    tags:
      - '**'
jobs:
  build:
    name: Build documentation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install node.js v16
        uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: Build docs
        run: npm install && npm run docs
